name: Electron Test

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Launch React
      working-directory: ./
      run: |
        npm start &
        sleep 10

    - name: Run headless test
      uses: coactions/setup-xvfb@v1
      with:
        run: npm test
        working-directory: ./
        options:

    - name: Upload Test Results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./test/
